default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: root
  password:
  host: localhost
  database: furima-40382_development

test:
  <<: *default
  username: root
  password:
  host: localhost
  database: furima-40382_test

production:
  <<: *default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>